### ISSUE TITLE
For ATSP files edge_data option is always "None"

### ISSUE THREAD

**Issue by ikurek** [malbarbo/tsplib-rs#1]
When I tried to parse ATSP files, with EDGE_TYPE: FULL MATRIX
`let edge_data = instance.edge_data.unwrap();`
always returned "None", and I wasn't able to acces AdjMatrix or EdgeMatrix. Am I doing something wrong? How else can I use this library for ATSP files?

**Comment by malbarbo** [comment]
I tried to organize the `Instance` structure according to the tsplib [documentation](http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/tsp95.pdf). `edge_data` is only available when `EDGE_DATA_FORMAT` is specified. When `EDGE_WEIGHT_FORMAT = FULL_MATRIX`, the edge weight will be stored in `edge_weight` field.
